#include "fonts/Linerama_Regular5pt7b.h"
#include "fonts/Linerama_Regular6pt7b.h"
#include "fonts/Linerama_Regular7pt7b.h"
#include "fonts/Linerama_Regular8pt7b.h"
#include "fonts/Linerama_Regular9pt7b.h"
#include "fonts/Linerama_Regular10pt7b.h"
#include "fonts/Linerama_Regular11pt7b.h"
#include "fonts/Linerama_Regular12pt7b.h"

#include "fonts/Linerama_Bold5pt7b.h"
#include "fonts/Linerama_Bold6pt7b.h"
#include "fonts/Linerama_Bold7pt7b.h"
#include "fonts/Linerama_Bold8pt7b.h"
#include "fonts/Linerama_Bold9pt7b.h"
#include "fonts/Linerama_Bold10pt7b.h"
#include "fonts/Linerama_Bold11pt7b.h"
#include "fonts/Linerama_Bold12pt7b.h"